export const GOOGLE_FONTS = [
  'Inter',
  'Lato',
  'Roboto',
  'Open Sans',
  'Nunito',
  'Poppins',
  'DM Sans',
  'Playfair Display',
  'Cormorant Garamond',
  'Montserrat',
  'Raleway',
  'Josefin Sans',
  'Libre Baskerville',
  'Anton',
  'Quicksand',
  'Cinzel',
  'Didact Gothic',
  'Source Sans Pro',
  'Fredoka',
  'Comic Neue',
  'Baloo 2',
  'Patrick Hand',
  'Sniglet'
];
