/**
 * Product Card Styles SSOT & Canonical Sequence Registry
 * Group 1: Base Store Themes (Protected — Never Touch, foundational DNA)
 * Group 2: Elessi Theme (10 Styles with exact element placements)
 */

export interface CardStyleOption {
  value: string;
  label: string;
  group: 'Base Store Themes (Protected)' | 'Elessi Theme' | 'Ella Theme';
  legacyKey: string;
  cssClass: string;
  description: string;
}

export const CARD_STYLE_OPTIONS: CardStyleOption[] = [
  // ── GROUP 1: BASE STORE THEMES (PROTECTED — DO NOT ALTER) ──────────────────
  {
    value: 'style1',
    label: 'Card 01 — Classic Standard Clean (Store Base)',
    group: 'Base Store Themes (Protected)',
    legacyKey: 'style1',
    cssClass: 'sc-std',
    description: 'Default clean store layout with circular action buttons. Baseline core DNA.',
  },
  {
    value: 'showcase_1',
    label: 'Card 02 — Neumorphic Soft Grey',
    group: 'Base Store Themes (Protected)',
    legacyKey: 'showcase_1',
    cssClass: 'sc1',
    description: 'Soft grey inner shadows with pill status badges.',
  },
  {
    value: 'showcase_8',
    label: 'Card 03 — Geometric Mondrian',
    group: 'Base Store Themes (Protected)',
    legacyKey: 'showcase_8',
    cssClass: 'sc8',
    description: 'High-contrast bold black borders and architectural structure.',
  },
  {
    value: 'showcase_11',
    label: 'Card 04 — Luxe Noir (Black & Gold)',
    group: 'Base Store Themes (Protected)',
    legacyKey: 'showcase_11',
    cssClass: 'sc11',
    description: 'Luxury dark mode with gold-bordered accents.',
  },
  {
    value: 'showcase_13',
    label: 'Card 05 — Soft Pastel Glow (Beauty)',
    group: 'Base Store Themes (Protected)',
    legacyKey: 'showcase_13',
    cssClass: 'sc13',
    description: 'Rose blush tone for cosmetics and beauty products.',
  },

  // ── GROUP 2: ELESSI THEME (10 STYLES) ───────────────────────────────────────
  {
    value: 'card_01',
    label: 'Elessi Style 1 (Corner FAB (+) & Side Rail)',
    group: 'Elessi Theme',
    legacyKey: 'showcase_22',
    cssClass: 'sc_style1',
    description: 'Unified side rail (Wishlist + Eye), bottom-left real sizes, and floating coral FAB (+) at the image seam.',
  },
  {
    value: 'card_02',
    label: 'Elessi Style 2 (Between-Seam 3-Icon Row)',
    group: 'Elessi Theme',
    legacyKey: 'showcase_23',
    cssClass: 'sc_style2',
    description: 'Horizontal row of 3 circular outline buttons between image and title: Bag, Wishlist, Quickview.',
  },
  {
    value: 'card_03',
    label: 'Elessi Style 3 (Bottom 3-Action Segmented Pill)',
    group: 'Elessi Theme',
    legacyKey: 'showcase_20',
    cssClass: 'sc_style3',
    description: 'White floating pill with fine dividers [ 🛍️ | 🤍 | 👁 ] centered at bottom of image.',
  },
  {
    value: 'card_04',
    label: 'Elessi Style 4 (Split Options Drawer [Choose options | 👁])',
    group: 'Elessi Theme',
    legacyKey: 'showcase_21',
    cssClass: 'sc_style4',
    description: 'Clean bottom split drawer [ Choose options ] button on left + square [ 👁 ] quick view button on right with wishlist.',
  },
  {
    value: 'card_05',
    label: 'Elessi Style 5 (3-Icon Vertical Right Rail)',
    group: 'Elessi Theme',
    legacyKey: 'showcase_12',
    cssClass: 'sc_style5',
    description: 'Vertical stack of 3 round white action buttons on right: Wishlist, Quickview, Add to Bag.',
  },
  {
    value: 'card_06',
    label: 'Elessi Style 6 (Seam Full-Width Black Cart Bar)',
    group: 'Elessi Theme',
    legacyKey: 'showcase_14',
    cssClass: 'sc_style6',
    description: 'Solid black full-width rectangular "Add to cart" bar at the image bottom seam + side action rail.',
  },
  {
    value: 'card_07',
    label: 'Elessi Style 7 (Floating 3-Bubble Center Row)',
    group: 'Elessi Theme',
    legacyKey: 'showcase_24',
    cssClass: 'sc_style7',
    description: '3 separate circular white buttons floating horizontally over image bottom center: Bag, Wishlist, Quickview.',
  },
  {
    value: 'card_08',
    label: 'Elessi Style 8 (Bottom Sticky Add to Cart Bar)',
    group: 'Elessi Theme',
    legacyKey: 'showcase_10',
    cssClass: 'sc_style8',
    description: 'Full-width coral rounded "Add to cart" button placed at the very bottom of the card with side rail.',
  },
  {
    value: 'card_09',
    label: 'Elessi Style 9 (In-Between Seam Add to Cart Bar)',
    group: 'Elessi Theme',
    legacyKey: 'showcase_16',
    cssClass: 'sc_style9',
    description: 'Coral rounded full-width "Add to cart" button placed between the image and the product title with side rail.',
  },
  {
    value: 'card_10',
    label: 'Elessi Style 10 (In-Card Quick Shop Sheet)',
    group: 'Elessi Theme',
    legacyKey: 'showcase_15',
    cssClass: 'sc_style10',
    description: 'In-card interactive sheet with real active color selector, real size options, quantity stepper [- 1 +], and Add to cart.',
  },

  // ── GROUP 3: ELLA THEME (8 STYLES) ────────────────────────────────────────
  {
    value: 'card_ella_01',
    label: 'Ella Style 1 (Clean Standard Clean)',
    group: 'Ella Theme',
    legacyKey: 'card_ella_01',
    cssClass: 'ella-card-01',
    description: 'Clean standard card with coral sale badge, stacked badges, top-right actions, and full-width bordered cart bar.',
  },
  {
    value: 'card_ella_02',
    label: 'Ella Style 2 (Airy Auto Parts)',
    group: 'Ella Theme',
    legacyKey: 'card_ella_02',
    cssClass: 'ella-card-02',
    description: 'Compact card with top-left wishlist, centered quick-view label, and persistent bordered add-to-cart bar.',
  },
  {
    value: 'card_ella_03',
    label: 'Ella Style 3 (Center Action Drawer)',
    group: 'Ella Theme',
    legacyKey: 'card_ella_03',
    cssClass: 'ella-card-03',
    description: 'Centered wishlist and navy add-to-cart action cluster with hover stars and bottom quick-view strip.',
  },
  {
    value: 'card_ella_04',
    label: 'Ella Style 4 (Split Wishlist Panel)',
    group: 'Ella Theme',
    legacyKey: 'card_ella_04',
    cssClass: 'ella-card-04',
    description: 'White action panel with quick-view top-right, bordered add-to-cart, and text wishlist action.',
  },
  {
    value: 'card_ella_05',
    label: 'Ella Style 5 (Gold Bordered Classic)',
    group: 'Ella Theme',
    legacyKey: 'card_ella_05',
    cssClass: 'ella-card-05',
    description: 'Gold sale badge, left-top content, top-right action stack, and wide white cart bar.',
  },
  {
    value: 'card_ella_06',
    label: 'Ella Style 6 (Side Rail Eyewear)',
    group: 'Ella Theme',
    legacyKey: 'card_ella_06',
    cssClass: 'ella-card-06',
    description: 'Compact eyewear card with right-side square action rail sliding in on hover or mobile focus.',
  },
  {
    value: 'card_ella_07',
    label: 'Ella Style 7 (Floating Action Row)',
    group: 'Ella Theme',
    legacyKey: 'card_ella_07',
    cssClass: 'ella-card-07',
    description: 'Pink sale typography, image arrows, and bottom-right three-icon action row.',
  },
  {
    value: 'card_ella_08',
    label: 'Ella Style 8 (Vertical Wig Rail)',
    group: 'Ella Theme',
    legacyKey: 'card_ella_08',
    cssClass: 'ella-card-08',
    description: 'Outlined sale badge with a vertical three-icon rail at bottom-right and responsive swatch handling.',
  },
];

export const LEGACY_CARD_STYLE_MAP: Record<string, string> = {
  // Base store themes aliases:
  style1: 'style1',
  card_11: 'style1',
  card_base_01: 'style1',
  showcase_1: 'showcase_1',
  card_12: 'showcase_1',
  card_base_02: 'showcase_1',
  showcase_8: 'showcase_8',
  card_13: 'showcase_8',
  card_base_03: 'showcase_8',
  showcase_11: 'showcase_11',
  card_14: 'showcase_11',
  card_base_04: 'showcase_11',
  showcase_13: 'showcase_13',
  card_15: 'showcase_13',
  card_base_05: 'showcase_13',
  // Elessi styles aliases:
  card_01: 'card_01',
  card_elessi_01: 'card_01',
  showcase_22: 'card_01',
  card_02: 'card_02',
  card_elessi_02: 'card_02',
  showcase_23: 'card_02',
  card_03: 'card_03',
  card_elessi_03: 'card_03',
  showcase_20: 'card_03',
  card_04: 'card_04',
  card_elessi_04: 'card_04',
  showcase_21: 'card_04',
  card_05: 'card_05',
  card_elessi_05: 'card_05',
  showcase_12: 'card_05',
  card_06: 'card_06',
  card_elessi_06: 'card_06',
  showcase_14: 'card_06',
  card_07: 'card_07',
  card_elessi_07: 'card_07',
  showcase_24: 'card_07',
  card_08: 'card_08',
  card_elessi_08: 'card_08',
  showcase_10: 'card_08',
  card_09: 'card_09',
  card_elessi_09: 'card_09',
  showcase_16: 'card_09',
  card_10: 'card_10',
  card_elessi_10: 'card_10',
  showcase_15: 'card_10',
  // Ella styles aliases:
  card_ella_01: 'card_ella_01',
  card_ella_02: 'card_ella_02',
  card_ella_03: 'card_ella_03',
  card_ella_04: 'card_ella_04',
  card_ella_05: 'card_ella_05',
  card_ella_06: 'card_ella_06',
  card_ella_07: 'card_ella_07',
  card_ella_08: 'card_ella_08',
};

export const STYLE_TO_CLASS_MAP: Record<string, string> = {
  // Base store themes classes:
  style1: 'sc-std',
  card_11: 'sc-std',
  card_base_01: 'sc-std',
  showcase_1: 'sc1',
  card_12: 'sc1',
  card_base_02: 'sc1',
  showcase_8: 'sc8',
  card_13: 'sc8',
  card_base_03: 'sc8',
  showcase_11: 'sc11',
  card_14: 'sc11',
  card_base_04: 'sc11',
  showcase_13: 'sc13',
  card_15: 'sc13',
  card_base_05: 'sc13',
  // Elessi styles classes:
  card_01: 'sc_style1',
  card_elessi_01: 'sc_style1',
  sc_style1: 'sc_style1',
  card_02: 'sc_style2',
  card_elessi_02: 'sc_style2',
  sc_style2: 'sc_style2',
  card_03: 'sc_style3',
  card_elessi_03: 'sc_style3',
  sc_style3: 'sc_style3',
  card_04: 'sc_style4',
  card_elessi_04: 'sc_style4',
  sc_style4: 'sc_style4',
  card_05: 'sc_style5',
  card_elessi_05: 'sc_style5',
  sc_style5: 'sc_style5',
  card_06: 'sc_style6',
  card_elessi_06: 'sc_style6',
  sc_style6: 'sc_style6',
  card_07: 'sc_style7',
  card_elessi_07: 'sc_style7',
  sc_style7: 'sc_style7',
  card_08: 'sc_style8',
  card_elessi_08: 'sc_style8',
  sc_style8: 'sc_style8',
  card_09: 'sc_style9',
  card_elessi_09: 'sc_style9',
  sc_style9: 'sc_style9',
  card_10: 'sc_style10',
  card_elessi_10: 'sc_style10',
  sc_style10: 'sc_style10',
  // Ella styles classes:
  card_ella_01: 'ella-card-01',
  card_ella_02: 'ella-card-02',
  card_ella_03: 'ella-card-03',
  card_ella_04: 'ella-card-04',
  card_ella_05: 'ella-card-05',
  card_ella_06: 'ella-card-06',
  card_ella_07: 'ella-card-07',
  card_ella_08: 'ella-card-08',
  // Direct lookups & legacy aliases:
  sc_athletic: 'sc_style1',
  sc_marketplace: 'sc_style2',
  sc_editorial: 'sc_style3',
  sc_flashdeal: 'sc_style4',
  sc_magazine: 'sc_style5',
  sc_polaroid: 'sc_style6',
  sc_roundcharm: 'sc_style7',
  sc_bottomsheet: 'sc_style8',
  sc_hangtag: 'sc_style9',
  sc_storyswipe: 'sc_style10',
  showcase_22: 'sc_style1',
  showcase_23: 'sc_style2',
  showcase_20: 'sc_style3',
  showcase_21: 'sc_style4',
  showcase_12: 'sc_style5',
  showcase_14: 'sc_style6',
  showcase_24: 'sc_style7',
  showcase_10: 'sc_style8',
  showcase_16: 'sc_style9',
  showcase_15: 'sc_style10',
};

export function normalizeCardStyle(style?: string | null): string {
  if (!style) return 'style1';
  return LEGACY_CARD_STYLE_MAP[style] || style;
}

export function getCardStyleClass(style?: string | null): string {
  if (!style) return 'sc-std';
  return STYLE_TO_CLASS_MAP[style] || STYLE_TO_CLASS_MAP[normalizeCardStyle(style)] || 'sc-std';
}
