import { StoreSettings } from '@/lib/types';
import { SettingsRow } from './types';

export const mapSettings = (row: SettingsRow): StoreSettings => ({
  id: row.id,
  storeName: row.store_name ?? (process.env.NEXT_PUBLIC_BRAND_NAME || 'Your Store'),
  storeUrl: row.store_url ?? '',
  whatsappNumber: row.whatsapp_number ?? '',
  currency: row.currency ?? 'PKR',
  currencySymbol: row.currency_symbol ?? 'Rs.',
  orderPrefix: row.order_prefix ?? 'ZE-',
  nextOrderSequence: row.next_order_sequence ?? 1,
  logoUrl: row.logo_url || undefined,
  logoWidth: row.logo_width ?? 120,
  bannerUrl: row.banner_url || undefined,
  faviconUrl: row.favicon_url || undefined,
  tagline: row.tagline || undefined,
  address: row.address || undefined,
  showStock: row.show_stock ?? false,
  showComparePrice: row.show_compare_price ?? true,
  enableSearch: row.enable_search ?? true,
  enableCategoryFilter: row.enable_category_filter ?? true,
  
  lastVercelPurge: row.last_vercel_purge || undefined,
  lastCloudflarePurge: row.last_cloudflare_purge || undefined,

  whatsappGreeting: row.whatsapp_greeting ?? 'Hello! I would like to order:',
  whatsappFooter: row.whatsapp_footer ?? 'Please confirm my order. Thank you!',
  metaTitle: row.meta_title || undefined,
  metaDescription: row.meta_description || undefined,
  footerText: row.footer_text || undefined,
  socialFacebook: row.social_facebook || undefined,
  socialInstagram: row.social_instagram || undefined,
  socialWhatsapp: row.social_whatsapp || undefined,
  socialYoutube: row.social_youtube || undefined,
  enableFakeViews: row.enable_fake_views ?? true,
  minViews: row.min_views ?? 10,
  maxViews: row.max_views ?? 50,
  enableTrustBadges: row.enable_trust_badges ?? true,
  deliveryEstimateText: row.delivery_estimate_text ?? 'Estimate delivery times: 3-5 days International.',
  freeShippingText: row.free_shipping_text ?? 'Free shipping & returns: On all orders over $150.',
  promoCodeText: row.promo_code_text ?? 'Use code "WELCOME15" for discount 15% on your first order.',
  enableSafeCheckout: row.enable_safe_checkout ?? true,
  safeCheckoutText: row.safe_checkout_text ?? 'Guarantee Safe Checkout:',
  safeCheckoutMethods: row.safe_checkout_methods ?? ['visa', 'mastercard', 'paypal', 'amex', 'klarna', 'cirrus', 'westernunion'],
  enableTicker: row.enable_ticker ?? false,
  tickerText: row.ticker_text ?? 'Free returns within 30 days\nUnlimited delivery for only $175',
  productDetailEnableTicker: row.product_detail_enable_ticker ?? false,
  productDetailTickerText: row.product_detail_ticker_text ?? 'Free returns within 30 days\nUnlimited delivery for only $175',
  enableVariantSwatches: row.enable_variant_swatches ?? true,
  swatchShape: (row.swatch_shape as 'circle' | 'square') ?? 'circle',
  swatchSize: (row.swatch_size as 'sm' | 'md' | 'lg') ?? 'md',
  swatchLimit: row.swatch_limit ?? 8,
  defaultVariantIndex: row.default_variant_index ?? 1,
  imageHoverStyle: (row.image_hover_style as 'second_image' | 'zoom' | 'slide_left' | 'zoom_swap' | 'fade_up' | 'blur_crossfade' | 'flip_3d' | 'none') ?? 'second_image',
  imageAspectRatio: row.image_aspect_ratio ?? '1:1',
  titleLineLimit: (row.title_line_limit as '1' | '2' | 'none') ?? '2',
  archiveSwatchSize: (row.archive_swatch_size as any) ?? 'md',
  productSwatchSize: (row.product_swatch_size as any) ?? 'md',
  archiveSwatchAlign: (row.archive_swatch_align as any) ?? 'left',
  enable_product_quick_whatsapp: row.enable_product_quick_whatsapp ?? true,
  headerSticky: row.header_sticky ?? true,
  headerStickyDesktop: row.header_sticky_desktop ?? true,
  headerStickyMobile: row.header_sticky_mobile ?? true,
  headerShowTopBar: row.header_show_top_bar ?? true,
  headerTopBarPhone: row.header_top_bar_phone ?? '',
  headerTopBarEmail: row.header_top_bar_email ?? '',
  headerShowNewsletter: row.header_show_newsletter ?? true,
  headerNewsletterText: row.header_newsletter_text ?? 'Summer sale discount off 50%. Shop Sale',
  headerTopBarBg: row.header_top_bar_bg ?? '#d97706',
  headerTopBarTextColor: row.header_top_bar_text_color ?? '#ffffff',
  headerBg: row.header_bg ?? '#ffffff',
  headerTextColor: row.header_text_color ?? '#1a1a2e',
  headerBorderColor: row.header_border_color ?? '#e5e7eb',
  headerDesktopLogoAlign: (row.header_desktop_logo_align as any) ?? 'left',
  headerDesktopSearchAlign: (row.header_desktop_search_align as any) ?? 'right',
  headerDesktopWishlistAlign: (row.header_desktop_wishlist_align as any) ?? 'right',
  headerDesktopCartAlign: (row.header_desktop_cart_align as any) ?? 'right',
  headerDesktopThemeAlign: (row.header_desktop_theme_align as any) ?? 'right',
  headerMobileLogoAlign: (row.header_mobile_logo_align as any) ?? 'center',
  headerMobileMenuAlign: (row.header_mobile_menu_align as any) ?? 'left',
  headerMobileSearchAlign: (row.header_mobile_search_align as any) ?? 'right',
  headerMobileCartAlign: (row.header_mobile_cart_align as any) ?? 'right',
  headerMobileWishlistAlign: (row.header_mobile_wishlist_align as any) ?? 'hidden',
  navigationMenu: Array.isArray(row.navigation_menu) ? row.navigation_menu : [],
  headerDesktopMenuAlign: (row.header_desktop_menu_align as any) ?? 'center',
  faqContent: row.faq_content ?? '',
  returnPolicyContent: row.return_policy_content ?? '',
  privacyPolicyContent: row.privacy_policy_content ?? '',
  showFaqInNav: row.show_faq_in_nav ?? true,
  showReturnsInNav: row.show_returns_in_nav ?? true,
  showPrivacyInNav: row.show_privacy_in_nav ?? true,
  showFaqInFooter: row.show_faq_in_footer ?? true,
  showReturnsInFooter: row.show_returns_in_footer ?? true,
  showPrivacyInFooter: row.show_privacy_in_footer ?? true,
  trustBadge1Title: row.trust_badge_1_title ?? 'Free Delivery',
  trustBadge1Desc: row.trust_badge_1_desc ?? 'On all orders above Rs. 2,000',
  trustBadge1Icon: row.trust_badge_1_icon ?? 'Truck',
  trustBadge2Title: row.trust_badge_2_title ?? 'Secure Payments',
  trustBadge2Desc: row.trust_badge_2_desc ?? '100% protected checkout payments',
  trustBadge2Icon: row.trust_badge_2_icon ?? 'Shield',
  trustBadge3Title: row.trust_badge_3_title ?? 'Easy Exchange',
  trustBadge3Desc: row.trust_badge_3_desc ?? 'No questions asked return policy',
  trustBadge3Icon: row.trust_badge_3_icon ?? 'RefreshCw',
  trustBadge4Title: row.trust_badge_4_title ?? '24/7 Support',
  trustBadge4Desc: row.trust_badge_4_desc ?? 'Call/WhatsApp anytime for assistance',
  trustBadge4Icon: row.trust_badge_4_icon ?? 'Phone',
  trustBadge1Enabled: row.trust_badge_1_enabled ?? true,
  trustBadge2Enabled: row.trust_badge_2_enabled ?? true,
  trustBadge3Enabled: row.trust_badge_3_enabled ?? true,
  trustBadge4Enabled: row.trust_badge_4_enabled ?? true,
  socialTiktok: row.social_tiktok || '',
  socialSnapchat: row.social_snapchat || '',
  socialTwitter: row.social_twitter || '',
  footerCol1Title: row.footer_col_1_title ?? 'About Our Store',
  footerCol2Title: row.footer_col_2_title ?? 'Customer Support',
  footerCol2Text: row.footer_col_2_text ?? 'Call/WhatsApp: \nEmail: \nTimings: 10 AM - 10 PM',
  footerCol3Title: row.footer_col_3_title ?? 'Quick Links',
  footerCol4Title: row.footer_col_4_title ?? 'Newsletter',
  footerCol4Text: row.footer_col_4_text ?? 'Subscribe to get special offers, free giveaways, and once-in-a-lifetime deals.',
  footerBottomText: row.footer_bottom_text ?? '',
  footerShowPayments: row.footer_show_payments ?? true,
  footerShowMenu: row.footer_show_menu ?? true,
  footerShowNewsletter: row.footer_show_newsletter ?? true,
  footerShowSocial: row.footer_show_social ?? true,
  floatingContactsEnabled: row.floating_contacts_enabled ?? true,
  floatingContactsPosition: (row.floating_contacts_position as any) ?? 'left',
  floatingContactsBottomMobile: row.floating_contacts_bottom_mobile ?? 80,
  floatingContactsBottomDesktop: row.floating_contacts_bottom_desktop ?? 24,
  floatingContactsSideMobile: row.floating_contacts_side_mobile ?? 16,
  floatingContactsSideDesktop: row.floating_contacts_side_desktop ?? 24,
  floatingContactsScale: row.floating_contacts_scale ? parseFloat(row.floating_contacts_scale.toString()) : 1.0,
  floatingWhatsappPreset: row.floating_whatsapp_preset ?? 'Hello! I am visiting your store and have a question.',
  floatingWhatsappNumber: row.floating_whatsapp_number ?? '',
  floatingWhatsappEnabled: row.floating_whatsapp_enabled ?? true,
  floatingInstagramEnabled: row.floating_instagram_enabled ?? true,
  floatingTiktokEnabled: row.floating_tiktok_enabled ?? false,
  floatingSnapchatEnabled: row.floating_snapchat_enabled ?? false,
  floatingTwitterEnabled: row.floating_twitter_enabled ?? false,

  exit_intent_enabled: row.exit_intent_enabled ?? false,
  exit_intent_title: row.exit_intent_title ?? 'Wait! Get a Special Discount',
  exit_intent_text: row.exit_intent_text ?? 'Submit your WhatsApp number to unlock a secret coupon code.',
  exit_intent_coupon: row.exit_intent_coupon ?? 'WELCOME10',
  spin_wheel_enabled: row.spin_wheel_enabled ?? false,
  spin_wheel_segments: Array.isArray(row.spin_wheel_segments) ? row.spin_wheel_segments : ['Try Again', '5% Off', 'Free Shipping', '10% Off', 'Free Delivery', 'WELCOME15'],
  cart_timer_minutes: row.cart_timer_minutes ?? 10,
  free_shipping_threshold: row.free_shipping_threshold ? parseFloat(row.free_shipping_threshold.toString()) : 2000.00,
  volume_discount_threshold: row.volume_discount_threshold ?? 3,
  volume_discount_percentage: row.volume_discount_percentage ? parseFloat(row.volume_discount_percentage.toString()) : 10.00,
  recent_buyers: typeof row.recent_buyers === 'string' ? JSON.parse(row.recent_buyers) : (row.recent_buyers ?? []),
  recently_viewed_limit: row.recently_viewed_limit ?? 4,
  recently_viewed_columns_desktop: row.recently_viewed_columns_desktop ?? 4,
  recently_viewed_columns_tablet: row.recently_viewed_columns_tablet ?? 3,
  recently_viewed_columns_mobile: row.recently_viewed_columns_mobile ?? 2,
  recently_viewed_title: row.recently_viewed_title ?? 'Recently Viewed',
  recently_viewed_subtitle: row.recently_viewed_subtitle ?? 'Products you have recently browsed',
  related_products_enabled: row.related_products_enabled ?? true,
  related_products_title: row.related_products_title ?? 'Related Products',
  related_products_subtitle: row.related_products_subtitle ?? 'You might also like these handpicked recommendations',
  related_products_limit: row.related_products_limit ?? 4,
  related_columns_desktop: row.related_columns_desktop ?? 4,
  related_columns_tablet: row.related_columns_tablet ?? 3,
  related_columns_mobile: row.related_columns_mobile ?? 2,
  shop_columns_desktop: row.shop_columns_desktop ?? 4,
  shop_columns_tablet: row.shop_columns_tablet ?? 3,
  shop_columns_mobile: row.shop_columns_mobile ?? 2,
  shop_category_chips_enabled: row.shop_category_chips_enabled ?? true,
  shop_infinite_scroll: row.shop_infinite_scroll ?? false,
  recent_buyers_enabled: row.recent_buyers_enabled ?? true,
  cookie_consent_enabled: row.cookie_consent_enabled ?? true,
  free_shipping_bar_enabled: row.free_shipping_bar_enabled ?? true,
  volume_discounts_enabled: row.volume_discounts_enabled ?? true,
  frequently_bought_together_enabled: row.frequently_bought_together_enabled ?? true,
  stock_urgency_enabled: row.stock_urgency_enabled ?? true,
  flash_sale_enabled: row.flash_sale_enabled ?? false,
  flash_sale_start_date: row.flash_sale_start_date || undefined,
  flash_sale_end_date: row.flash_sale_end_date || undefined,
  globalFlashSaleDiscountType: (row.global_flash_sale_discount_type as any) || 'percentage',
  globalFlashSaleDiscountValue: row.global_flash_sale_discount_value ? parseFloat(row.global_flash_sale_discount_value.toString()) : 0,
  social_feeds_enabled: row.social_feeds_enabled ?? true,
  cart_timer_enabled: row.cart_timer_enabled ?? true,
  size_guide_enabled: row.size_guide_enabled ?? true,

  recent_buyers_names: row.recent_buyers_names ?? 'Ahmad, Fatima, Zainab, Hamza, Ayesha, Bilal, Sana, Ali, Usman, Maryam',
  recent_buyers_cities: row.recent_buyers_cities ?? 'Lahore, Karachi, Islamabad, Rawalpindi, Faisalabad, Multan, Peshawar, Quetta, Sialkot, Gujranwala',
  recent_buyers_source: (row.recent_buyers_source as any) ?? 'simulated',
  recent_buyers_product_pool: (row.recent_buyers_product_pool as any) ?? 'any',
  recent_buyers_custom_products: typeof row.recent_buyers_custom_products === 'string' ? JSON.parse(row.recent_buyers_custom_products) : (row.recent_buyers_custom_products ?? []),
  recent_buyers_initial_delay: row.recent_buyers_initial_delay ?? 15,
  recent_buyers_interval: row.recent_buyers_interval ?? 35,
  recent_buyers_display_duration: row.recent_buyers_display_duration ?? 6,
  recent_buyers_show_on_checkout: row.recent_buyers_show_on_checkout ?? false,
  exit_intent_image_url: row.exit_intent_image_url ?? '',
  exit_intent_delay_mobile: row.exit_intent_delay_mobile ?? 25,
  cookie_consent_text: row.cookie_consent_text ?? 'We use cookies to optimize your experience, analyze traffic, and support checkout flows. By continuing, you agree to our privacy policy.',
  cookie_consent_button_text: row.cookie_consent_button_text ?? 'Accept All',
  social_feeds_homepage_enabled: row.social_feeds_homepage_enabled ?? true,
  social_feeds_product_enabled: row.social_feeds_product_enabled ?? true,
  social_feeds_title: row.social_feeds_title ?? 'Follow Us On Instagram',
  social_feeds_subtitle: row.social_feeds_subtitle ?? '@YourStore',
  social_feeds_desc: row.social_feeds_desc ?? 'Tag us in your post to get featured on our page',
  social_feeds_items: typeof row.social_feeds_items === 'string' ? JSON.parse(row.social_feeds_items) : (row.social_feeds_items ?? []),
  cart_timer_message: row.cart_timer_message ?? 'Items in your cart are reserved for {timer} minutes.',
  coupon_codes_enabled: row.coupon_codes_enabled ?? true,
  productPageLayout: row.product_page_layout ?? ['details', 'ticker', 'reviews', 'related', 'recently_viewed', 'social_feed'],
  card_style: (row.card_style as any) ?? 'style1',
  card_variant: (row.card_variant as any) ?? 'v1',
  card_show_stars: row.card_show_stars ?? true,
  card_show_quickview: row.card_show_quickview ?? true,
  card_show_wishlist: row.card_show_wishlist ?? true,
  card_show_quickcart: row.card_show_quickcart ?? true,
  card_show_description: row.card_show_description ?? true,
  card_show_swatches: row.card_show_swatches ?? true,
  card_show_sizes: row.card_show_sizes ?? true,
  card_show_materials: row.card_show_materials ?? true,
  card_show_custom: row.card_show_custom ?? true,
  card_show_custom_2: row.card_show_custom_2 ?? true,
  card_show_type_color: row.card_show_type_color ?? true,
  card_show_type_size: row.card_show_type_size ?? true,
  card_show_type_material: row.card_show_type_material ?? true,
  card_show_type_custom: row.card_show_type_custom ?? true,
  card_alignment: (row.card_alignment as any) ?? 'left',
  card_elements_order: row.card_elements_order ?? ['title', 'rating', 'price', 'swatches'],
  card_mobile_columns: row.card_mobile_columns ?? 2,
  theme_preset: row.theme_preset ?? 'classic_white',
  theme_config: typeof row.theme_config === 'string' ? JSON.parse(row.theme_config) : (row.theme_config ?? undefined),

  meta_pixel_id: row.meta_pixel_id ?? '',
  meta_sync_enabled: row.meta_sync_enabled ?? false,
  ga4_measurement_id: row.ga4_measurement_id ?? '',
  gtm_container_id: row.gtm_container_id ?? '',
  tiktok_pixel_id: row.tiktok_pixel_id ?? '',
  twitter_pixel_id: row.twitter_pixel_id ?? '',
  snapchat_pixel_id: row.snapchat_pixel_id ?? '',
  pinterest_tag_id: row.pinterest_tag_id ?? '',

  twitter_handle: row.twitter_handle ?? '',
  meta_title_suffix: row.meta_title_suffix ?? '',

  ai_enabled: row.ai_enabled ?? false,
  ai_model_credentials: typeof row.ai_model_credentials === 'string' ? JSON.parse(row.ai_model_credentials) : (row.ai_model_credentials ?? {}),
  ai_persona_config: typeof row.ai_persona_config === 'string' ? JSON.parse(row.ai_persona_config) : (row.ai_persona_config ?? {}),
  content_provider: row.content_provider ?? 'groq',
  content_model: row.content_model ?? 'llama-3.3-70b-versatile',
  content_keys: row.content_keys ?? '',
  vision_provider: row.vision_provider ?? 'gemini',
  vision_model: (row.vision_model && !row.vision_model.includes('2.5') && !row.vision_model.includes('1.5') && !row.vision_model.includes('2.0') && !row.vision_model.includes('3.5') && !row.vision_model.includes('3.1')) ? row.vision_model : 'gemini-3.6-flash',
  vision_keys: row.vision_keys ?? '',
  ai_tone: row.ai_tone ?? 'Professional',
  ai_language: row.ai_language ?? 'English',
  ai_custom_instructions: row.ai_custom_instructions ?? '',
  auto_content_seo: row.auto_content_seo ?? true,
  auto_media_ai: row.auto_media_ai ?? true,
  target_audiences: row.target_audiences ?? '',
  product_types: row.product_types ?? '',
  category_default_template: row.category_default_template ?? '',
  product_default_template: row.product_default_template ?? '',
  category_description_prompt: row.category_description_prompt ?? '',
  category_description_limit: row.category_description_limit ?? 150,
  product_description_prompt: row.product_description_prompt ?? '',
  product_description_limit: row.product_description_limit ?? 250,
  product_short_prompt: row.product_short_prompt ?? '',
  product_short_limit: row.product_short_limit ?? 100,
  collection_default_template: row.collection_default_template ?? '',
  collection_description_prompt: row.collection_description_prompt ?? 'Write an engaging collection overview inspired by: Explore our exclusively curated collection, featuring premium styles, soft fabrics, and comfortable fits.',
  collection_description_limit: row.collection_description_limit ?? 80,

  smtp_email: row.smtp_email ?? '',
  smtp_app_password: row.smtp_app_password ?? '',
  smtp_from_name: row.smtp_from_name ?? '',
  admin_notification_email: row.admin_notification_email ?? '',
  email_notifications: typeof row.email_notifications === 'string' ? JSON.parse(row.email_notifications) : (row.email_notifications ?? undefined),
  low_stock_threshold: row.low_stock_threshold ?? 5,
  abandonedCartEmailEnabled: row.abandoned_cart_email_enabled ?? false,
  abandonedCartAdminNotify: row.abandoned_cart_admin_notify ?? false,
  abandonedCartEmailSubject: row.abandoned_cart_email_subject ?? 'You left items in your cart!',
  abandonedCartEmailTemplate: row.abandoned_cart_email_template ?? 'Hi {{name}},\n\nYou left some items in your cart. Complete your purchase here:\n{{checkout_url}}',
  popularSearches: row.popular_searches ?? 'Co-ord Sets, Sonic, Graphic Tee, T-shirt, Kids',

  postex_enabled: row.postex_enabled ?? false,
  postex_api_token: row.postex_api_token ?? '',
  postex_mode: row.postex_mode ?? 'sandbox',
  postex_pickup_address: row.postex_pickup_address ?? '',
  postex_return_address: row.postex_return_address ?? '',
  postex_order_type: row.postex_order_type ?? '',
  postex_handling_type: row.postex_handling_type ?? '',
  postex_default_remarks: row.postex_default_remarks ?? '',
  postex_pickup_display: row.postex_pickup_display ?? '',
  postex_return_display: row.postex_return_display ?? '',
  postex_return_city: row.postex_return_city ?? '',
  postex_product_check: row.postex_product_check ?? '1',
  postex_sku_check: row.postex_sku_check ?? '0',
  postex_weight_check: row.postex_weight_check ?? '1',
  postex_pieces_check: row.postex_pieces_check ?? '1',
  postex_cod_check: row.postex_cod_check ?? '0',
  postex_notes_check: row.postex_notes_check ?? '1',
  postex_default_weight: row.postex_default_weight ?? '0.5',
  postex_default_items: row.postex_default_items ?? '3',
  postex_default_product: row.postex_default_product ?? 'General Items',
  postex_whatsapp_template: row.postex_whatsapp_template ?? 'Dear {name}, your order has been booked. You can track it here: {url}\n{note}',
  postex_whatsapp_note: row.postex_whatsapp_note ?? 'Thank you for shopping with us!',
  postex_auto_download_label: row.postex_auto_download_label ?? false,

  updatedAt: row.updated_at
});
