import { StoreSettings } from '@/lib/types';
import { SettingsRow } from './types';

export const mapSettings = (row: SettingsRow): StoreSettings => ({
  id: row.id,
  store_name: row.store_name ?? (process.env.NEXT_PUBLIC_BRAND_NAME || 'Your Store'),
  store_url: row.store_url ?? '',
  whatsapp_number: row.whatsapp_number ?? '',
  currency: row.currency ?? 'PKR',
  currency_symbol: row.currency_symbol ?? 'Rs.',
  order_prefix: row.order_prefix ?? 'ZE-',
  next_order_sequence: row.next_order_sequence ?? 1,
  logo_url: row.logo_url || undefined,
  logo_width: row.logo_width ?? 120,
  banner_url: row.banner_url || undefined,
  favicon_url: row.favicon_url || undefined,
  tagline: row.tagline || undefined,
  address: row.address || undefined,
  show_stock: row.show_stock ?? false,
  show_compare_price: row.show_compare_price ?? true,
  enable_search: row.enable_search ?? true,
  mobile_bottom_nav_enabled: row.mobile_bottom_nav_enabled ?? true,
  mobile_bottom_nav_show_labels: row.mobile_bottom_nav_show_labels ?? true,
  mobile_bottom_nav_items: row.mobile_bottom_nav_items ?? null,
  cart_bar_enabled: row.cart_bar_enabled ?? true,
  enable_category_filter: row.enable_category_filter ?? true,
  
  last_vercel_purge: row.last_vercel_purge || undefined,
  last_cloudflare_purge: row.last_cloudflare_purge || undefined,

  whatsapp_greeting: row.whatsapp_greeting ?? 'Hello! I would like to order:',
  whatsapp_footer: row.whatsapp_footer ?? 'Please confirm my order. Thank you!',
  meta_title: row.meta_title || undefined,
  meta_description: row.meta_description || undefined,
  footer_text: row.footer_text || undefined,
  social_facebook: row.social_facebook || undefined,
  social_instagram: row.social_instagram || undefined,
  social_whatsapp: row.social_whatsapp || undefined,
  social_youtube: row.social_youtube || undefined,
  enable_fake_views: row.enable_fake_views ?? true,
  min_views: row.min_views ?? 10,
  max_views: row.max_views ?? 50,
  enable_trust_badges: row.enable_trust_badges ?? true,
  delivery_estimate_text: row.delivery_estimate_text ?? 'Estimate delivery times: 3-5 days International.',
  free_shipping_text: row.free_shipping_text ?? 'Free shipping & returns: On all orders over $150.',
  promo_code_text: row.promo_code_text ?? 'Use code "WELCOME15" for discount 15% on your first order.',
  enable_safe_checkout: row.enable_safe_checkout ?? true,
  safe_checkout_text: row.safe_checkout_text ?? 'Guarantee Safe Checkout:',
  safe_checkout_methods: row.safe_checkout_methods ?? ['visa', 'mastercard', 'paypal', 'amex', 'klarna', 'cirrus', 'westernunion'],
  enable_ticker: row.enable_ticker ?? false,
  ticker_text: row.ticker_text ?? 'Free returns within 30 days\nUnlimited delivery for only $175',
  product_detail_enable_ticker: row.product_detail_enable_ticker ?? false,
  product_detail_ticker_text: row.product_detail_ticker_text ?? 'Free returns within 30 days\nUnlimited delivery for only $175',
  enable_variant_swatches: row.enable_variant_swatches ?? true,
  swatch_shape: (row.swatch_shape as 'circle' | 'square') ?? 'circle',
  swatch_size: (row.swatch_size as 'sm' | 'md' | 'lg') ?? 'md',
  swatch_limit: row.swatch_limit ?? 8,
  default_variant_index: row.default_variant_index ?? 1,
  image_hover_style: (row.image_hover_style as 'second_image' | 'zoom' | 'slide_left' | 'zoom_swap' | 'fade_up' | 'blur_crossfade' | 'flip_3d' | 'none') ?? 'second_image',
  image_aspect_ratio: row.image_aspect_ratio ?? '1:1',
  title_line_limit: (row.title_line_limit as '1' | '2' | 'none') ?? '2',
  archive_swatch_size: (row.archive_swatch_size as any) ?? 'md',
  product_swatch_size: (row.product_swatch_size as any) ?? 'md',
  archive_swatch_align: (row.archive_swatch_align as any) ?? 'left',
  enable_product_quick_whatsapp: row.enable_product_quick_whatsapp ?? true,
  header_sticky: row.header_sticky ?? true,
  header_sticky_desktop: row.header_sticky_desktop ?? true,
  header_sticky_mobile: row.header_sticky_mobile ?? true,
  header_show_top_bar: row.header_show_top_bar ?? true,
  header_top_bar_phone: row.header_top_bar_phone ?? '',
  header_top_bar_email: row.header_top_bar_email ?? '',
  header_show_newsletter: row.header_show_newsletter ?? true,
  header_newsletter_text: row.header_newsletter_text ?? 'Summer sale discount off 50%. Shop Sale',
  header_top_bar_bg: row.header_top_bar_bg ?? '#d97706',
  header_top_bar_text_color: row.header_top_bar_text_color ?? '#ffffff',
  header_bg: row.header_bg ?? '#ffffff',
  header_text_color: row.header_text_color ?? '#1a1a2e',
  header_border_color: row.header_border_color ?? '#e5e7eb',
  header_desktop_logo_align: (row.header_desktop_logo_align as any) ?? 'left',
  header_desktop_search_align: (row.header_desktop_search_align as any) ?? 'right',
  header_desktop_wishlist_align: (row.header_desktop_wishlist_align as any) ?? 'right',
  header_desktop_cart_align: (row.header_desktop_cart_align as any) ?? 'right',
  header_desktop_theme_align: (row.header_desktop_theme_align as any) ?? 'right',
  header_mobile_logo_align: (row.header_mobile_logo_align as any) ?? 'center',
  header_mobile_menu_align: (row.header_mobile_menu_align as any) ?? 'left',
  header_mobile_search_align: (row.header_mobile_search_align as any) ?? 'right',
  header_mobile_cart_align: (row.header_mobile_cart_align as any) ?? 'right',
  header_mobile_wishlist_align: (row.header_mobile_wishlist_align as any) ?? 'hidden',
  navigation_menu: Array.isArray(row.navigation_menu) ? row.navigation_menu : [],
  header_desktop_menu_align: (row.header_desktop_menu_align as any) ?? 'center',
  faq_content: row.faq_content ?? '',
  return_policy_content: row.return_policy_content ?? '',
  privacy_policy_content: row.privacy_policy_content ?? '',
  show_faq_in_nav: row.show_faq_in_nav ?? true,
  show_returns_in_nav: row.show_returns_in_nav ?? true,
  show_privacy_in_nav: row.show_privacy_in_nav ?? true,
  show_faq_in_footer: row.show_faq_in_footer ?? true,
  show_returns_in_footer: row.show_returns_in_footer ?? true,
  show_privacy_in_footer: row.show_privacy_in_footer ?? true,
  trust_badge1_title: row.trust_badge_1_title ?? 'Free Delivery',
  trust_badge1_desc: row.trust_badge_1_desc ?? 'On all orders above Rs. 2,000',
  trust_badge1_icon: row.trust_badge_1_icon ?? 'Truck',
  trust_badge2_title: row.trust_badge_2_title ?? 'Secure Payments',
  trust_badge2_desc: row.trust_badge_2_desc ?? '100% protected checkout payments',
  trust_badge2_icon: row.trust_badge_2_icon ?? 'Shield',
  trust_badge3_title: row.trust_badge_3_title ?? 'Easy Exchange',
  trust_badge3_desc: row.trust_badge_3_desc ?? 'No questions asked return policy',
  trust_badge3_icon: row.trust_badge_3_icon ?? 'RefreshCw',
  trust_badge4_title: row.trust_badge_4_title ?? '24/7 Support',
  trust_badge4_desc: row.trust_badge_4_desc ?? 'Call/WhatsApp anytime for assistance',
  trust_badge4_icon: row.trust_badge_4_icon ?? 'Phone',
  trust_badge1_enabled: row.trust_badge_1_enabled ?? true,
  trust_badge2_enabled: row.trust_badge_2_enabled ?? true,
  trust_badge3_enabled: row.trust_badge_3_enabled ?? true,
  trust_badge4_enabled: row.trust_badge_4_enabled ?? true,
  social_tiktok: row.social_tiktok || '',
  social_snapchat: row.social_snapchat || '',
  social_twitter: row.social_twitter || '',
  footer_col1_title: row.footer_col_1_title ?? 'About Our Store',
  footer_col2_title: row.footer_col_2_title ?? 'Customer Support',
  footer_col2_text: row.footer_col_2_text ?? 'Call/WhatsApp: \nEmail: \nTimings: 10 AM - 10 PM',
  footer_col3_title: row.footer_col_3_title ?? 'Quick Links',
  footer_col4_title: row.footer_col_4_title ?? 'Newsletter',
  footer_col4_text: row.footer_col_4_text ?? 'Subscribe to get special offers, free giveaways, and once-in-a-lifetime deals.',
  footer_bottom_text: row.footer_bottom_text ?? '',
  footer_bg: row.footer_bg ?? undefined,
  footer_text_color: row.footer_text_color ?? undefined,
  footer_border_color: row.footer_border_color ?? undefined,
  footer_heading_color: row.footer_heading_color ?? undefined,
  footer_link_color: row.footer_link_color ?? undefined,
  footer_copyright_color: row.footer_copyright_color ?? undefined,
  footer_show_payments: row.footer_show_payments ?? true,
  footer_show_menu: row.footer_show_menu ?? true,
  footer_show_newsletter: row.footer_show_newsletter ?? true,
  footer_show_social: row.footer_show_social ?? true,
  floating_contacts_enabled: row.floating_contacts_enabled ?? true,
  floating_contacts_position: (row.floating_contacts_position as any) ?? 'left',
  floating_contacts_bottom_mobile: row.floating_contacts_bottom_mobile ?? 80,
  floating_contacts_bottom_desktop: row.floating_contacts_bottom_desktop ?? 24,
  floating_contacts_side_mobile: row.floating_contacts_side_mobile ?? 16,
  floating_contacts_side_desktop: row.floating_contacts_side_desktop ?? 24,
  floating_contacts_scale: row.floating_contacts_scale ? parseFloat(row.floating_contacts_scale.toString()) : 1.0,
  floating_whatsapp_preset: row.floating_whatsapp_preset ?? 'Hello! I am visiting your store and have a question.',
  floating_whatsapp_number: row.floating_whatsapp_number ?? '',
  floating_whatsapp_enabled: row.floating_whatsapp_enabled ?? true,
  floating_instagram_enabled: row.floating_instagram_enabled ?? true,
  floating_tiktok_enabled: row.floating_tiktok_enabled ?? false,
  floating_snapchat_enabled: row.floating_snapchat_enabled ?? false,
  floating_twitter_enabled: row.floating_twitter_enabled ?? false,

  exit_intent_enabled: row.exit_intent_enabled ?? false,
  exit_intent_title: row.exit_intent_title ?? 'Wait! Get a Special Discount',
  exit_intent_text: row.exit_intent_text ?? 'Submit your WhatsApp number to unlock a secret coupon code.',
  exit_intent_coupon: row.exit_intent_coupon ?? 'WELCOME10',
  spin_wheel_enabled: row.spin_wheel_enabled ?? false,
  spin_wheel_segments: Array.isArray(row.spin_wheel_segments) ? row.spin_wheel_segments : ['Try Again', '5% Off', 'Free Shipping', '10% Off', 'Free Delivery', 'WELCOME15'],
  cart_timer_minutes: row.cart_timer_minutes ?? 10,
  free_shipping_threshold: row.free_shipping_threshold ? parseFloat(row.free_shipping_threshold.toString()) : 2000.00,
  volume_discount_threshold: row.volume_discount_threshold ?? 3,
  volume_discount_percentage: row.volume_discount_percentage ? parseFloat(row.volume_discount_percentage.toString()) : 10.00,
  recent_buyers: typeof row.recent_buyers === 'string' ? JSON.parse(row.recent_buyers) : (row.recent_buyers ?? []),
  recently_viewed_limit: row.recently_viewed_limit ?? 4,
  recently_viewed_columns_desktop: row.recently_viewed_columns_desktop ?? 4,
  recently_viewed_columns_tablet: row.recently_viewed_columns_tablet ?? 3,
  recently_viewed_columns_mobile: row.recently_viewed_columns_mobile ?? 2,
  recently_viewed_title: row.recently_viewed_title ?? 'Recently Viewed',
  recently_viewed_subtitle: row.recently_viewed_subtitle ?? 'Products you have recently browsed',
  related_products_enabled: row.related_products_enabled ?? true,
  premium_themes_enabled: row.premium_themes_enabled ?? false,
  related_products_title: row.related_products_title ?? 'Related Products',
  related_products_subtitle: row.related_products_subtitle ?? 'You might also like these handpicked recommendations',
  related_products_limit: row.related_products_limit ?? 4,
  related_columns_desktop: row.related_columns_desktop ?? 4,
  related_columns_tablet: row.related_columns_tablet ?? 3,
  related_columns_mobile: row.related_columns_mobile ?? 2,
  shop_columns_desktop: row.shop_columns_desktop ?? 4,
  shop_columns_tablet: row.shop_columns_tablet ?? 3,
  shop_columns_mobile: row.shop_columns_mobile ?? 2,
  shop_products_per_page: (row as any).shop_products_per_page ?? 12,
  shop_products_per_page_desktop: (row as any).shop_products_per_page_desktop ?? 12,
  shop_products_per_page_tablet: (row as any).shop_products_per_page_tablet ?? 9,
  shop_products_per_page_mobile: (row as any).shop_products_per_page_mobile ?? 6,
  shop_category_chips_enabled: row.shop_category_chips_enabled ?? true,
  shop_infinite_scroll: row.shop_infinite_scroll ?? false,
  shop_grid_gap: (row.shop_grid_gap as 'tight' | 'normal' | 'relaxed') ?? 'normal',
  shop_show_breadcrumbs: row.shop_show_breadcrumbs ?? true,
  recent_buyers_enabled: row.recent_buyers_enabled ?? true,
  cookie_consent_enabled: row.cookie_consent_enabled ?? true,
  free_shipping_bar_enabled: row.free_shipping_bar_enabled ?? true,
  volume_discounts_enabled: row.volume_discounts_enabled ?? true,
  frequently_bought_together_enabled: row.frequently_bought_together_enabled ?? true,
  stock_urgency_enabled: row.stock_urgency_enabled ?? true,
  flash_sale_enabled: row.flash_sale_enabled ?? false,
  flash_sale_start_date: row.flash_sale_start_date || undefined,
  flash_sale_end_date: row.flash_sale_end_date || undefined,
  global_flash_sale_discount_type: (row.global_flash_sale_discount_type as any) || 'percentage',
  global_flash_sale_discount_value: row.global_flash_sale_discount_value ? parseFloat(row.global_flash_sale_discount_value.toString()) : 0,
  social_feeds_enabled: row.social_feeds_enabled ?? true,
  cart_timer_enabled: row.cart_timer_enabled ?? true,
  size_guide_enabled: row.size_guide_enabled ?? true,

  recent_buyers_names: row.recent_buyers_names ?? 'Ahmad, Fatima, Zainab, Hamza, Ayesha, Bilal, Sana, Ali, Usman, Maryam',
  recent_buyers_cities: row.recent_buyers_cities ?? 'Lahore, Karachi, Islamabad, Rawalpindi, Faisalabad, Multan, Peshawar, Quetta, Sialkot, Gujranwala',
  recent_buyers_source: (row.recent_buyers_source as any) ?? 'simulated',
  recent_buyers_product_pool: (row.recent_buyers_product_pool as any) ?? 'any',
  recent_buyers_custom_products: typeof row.recent_buyers_custom_products === 'string' ? JSON.parse(row.recent_buyers_custom_products) : (row.recent_buyers_custom_products ?? []),
  recent_buyers_initial_delay: row.recent_buyers_initial_delay ?? 15,
  recent_buyers_interval: row.recent_buyers_interval ?? 35,
  recent_buyers_display_duration: row.recent_buyers_display_duration ?? 6,
  recent_buyers_show_on_checkout: row.recent_buyers_show_on_checkout ?? false,
  exit_intent_image_url: row.exit_intent_image_url ?? '',
  exit_intent_delay_mobile: row.exit_intent_delay_mobile ?? 25,
  cookie_consent_text: row.cookie_consent_text ?? 'We use cookies to optimize your experience, analyze traffic, and support checkout flows. By continuing, you agree to our privacy policy.',
  cookie_consent_button_text: row.cookie_consent_button_text ?? 'Accept All',
  social_feeds_homepage_enabled: row.social_feeds_homepage_enabled ?? true,
  social_feeds_product_enabled: row.social_feeds_product_enabled ?? true,
  social_feeds_title: row.social_feeds_title ?? 'Follow Us On Instagram',
  social_feeds_subtitle: row.social_feeds_subtitle ?? '@YourStore',
  social_feeds_desc: row.social_feeds_desc ?? 'Tag us in your post to get featured on our page',
  social_feeds_items: typeof row.social_feeds_items === 'string' ? JSON.parse(row.social_feeds_items) : (row.social_feeds_items ?? []),
  cart_timer_message: row.cart_timer_message ?? 'Items in your cart are reserved for {timer} minutes.',
  coupon_codes_enabled: row.coupon_codes_enabled ?? true,
  product_page_layout: row.product_page_layout ?? ['details', 'ticker', 'reviews', 'related', 'recently_viewed', 'social_feed'],
  product_page_hidden_blocks: row.product_page_hidden_blocks ?? [],
  card_style: (row.card_style as any) ?? 'style1',
  card_mobile_activation: (row.card_mobile_activation as 'scroll' | 'touch' | 'off') ?? 'scroll',
  card_shadow: (row.card_shadow as 'none' | 'sm' | 'md' | 'lg') ?? 'sm',
  card_hover_lift: row.card_hover_lift ?? true,
  card_border_enabled: row.card_border_enabled ?? true,
  card_image_fit: (row.card_image_fit as 'contain' | 'cover') ?? 'contain',
  card_compare_color: row.card_compare_color ?? '#ef4444',
  card_sale_price_color: row.card_sale_price_color ?? '',
  card_variant: (row.card_variant as any) ?? 'v1',
  card_show_stars: row.card_show_stars ?? true,
  card_show_quickview: row.card_show_quickview ?? true,
  card_show_wishlist: row.card_show_wishlist ?? true,
  card_show_quickcart: row.card_show_quickcart ?? true,
  card_show_description: row.card_show_description ?? true,
  card_show_swatches: row.card_show_swatches ?? true,
  card_show_sizes: row.card_show_sizes ?? true,
  card_show_materials: row.card_show_materials ?? true,
  card_show_custom: row.card_show_custom ?? true,
  card_show_custom_2: row.card_show_custom_2 ?? true,
  card_show_type_color: row.card_show_type_color ?? true,
  card_show_type_size: row.card_show_type_size ?? true,
  card_show_type_material: row.card_show_type_material ?? true,
  card_show_type_custom: row.card_show_type_custom ?? true,
  card_alignment: (row.card_alignment as any) ?? 'left',
  card_elements_order: row.card_elements_order ?? ['title', 'rating', 'price', 'swatches'],
  card_mobile_columns: row.card_mobile_columns ?? 2,
  theme_preset: row.theme_preset ?? 'classic_white',
  theme_config: typeof row.theme_config === 'string' ? JSON.parse(row.theme_config) : (row.theme_config ?? undefined),

  meta_pixel_id: row.meta_pixel_id ?? '',
  meta_sync_enabled: row.meta_sync_enabled ?? false,
  ga4_measurement_id: row.ga4_measurement_id ?? '',
  gtm_container_id: row.gtm_container_id ?? '',
  tiktok_pixel_id: row.tiktok_pixel_id ?? '',
  twitter_pixel_id: row.twitter_pixel_id ?? '',
  snapchat_pixel_id: row.snapchat_pixel_id ?? '',
  pinterest_tag_id: row.pinterest_tag_id ?? '',

  twitter_handle: row.twitter_handle ?? '',
  meta_title_suffix: row.meta_title_suffix ?? '',

  ai_enabled: row.ai_enabled ?? false,
  // SECRET — intentionally NOT mapped to client-facing StoreSettings (Pass 6 leak fix).
  // Read server-side via lib/services/settings/server-secrets or getAISettings:
  // ai_model_credentials, content_keys, vision_keys, smtp_app_password, postex_api_token.
  ai_persona_config: typeof row.ai_persona_config === 'string' ? JSON.parse(row.ai_persona_config) : (row.ai_persona_config ?? {}),
  content_provider: row.content_provider ?? 'groq',
  content_model: row.content_model ?? 'llama-3.3-70b-versatile',
  vision_provider: row.vision_provider ?? 'gemini',
  vision_model: row.vision_model || 'gemini-3-flash-preview',
  ai_tone: row.ai_tone ?? 'Professional',
  ai_language: row.ai_language ?? 'English',
  ai_custom_instructions: row.ai_custom_instructions ?? '',
  auto_content_seo: row.auto_content_seo ?? true,
  auto_media_ai: row.auto_media_ai ?? true,
  target_audiences: row.target_audiences ?? '',
  product_types: row.product_types ?? '',
  category_default_template: row.category_default_template ?? '',
  product_default_template: row.product_default_template ?? '',
  category_description_prompt: row.category_description_prompt ?? '',
  category_description_limit: row.category_description_limit ?? 150,
  product_description_prompt: row.product_description_prompt ?? '',
  product_description_limit: row.product_description_limit ?? 250,
  product_short_prompt: row.product_short_prompt ?? '',
  product_short_limit: row.product_short_limit ?? 100,
  collection_default_template: row.collection_default_template ?? '',
  collection_description_prompt: row.collection_description_prompt ?? 'Write an engaging collection overview inspired by: Explore our exclusively curated collection, featuring premium styles, soft fabrics, and comfortable fits.',
  collection_description_limit: row.collection_description_limit ?? 80,

  smtp_email: row.smtp_email ?? '',
  smtp_from_name: row.smtp_from_name ?? '',
  admin_notification_email: row.admin_notification_email ?? '',
  email_notifications: typeof row.email_notifications === 'string' ? JSON.parse(row.email_notifications) : (row.email_notifications ?? undefined),
  low_stock_threshold: row.low_stock_threshold ?? 5,
  abandoned_cart_email_enabled: row.abandoned_cart_email_enabled ?? false,
  abandoned_cart_admin_notify: row.abandoned_cart_admin_notify ?? false,
  abandoned_cart_email_subject: row.abandoned_cart_email_subject ?? 'You left items in your cart!',
  abandoned_cart_email_template: row.abandoned_cart_email_template ?? 'Hi {{name}},\n\nYou left some items in your cart. Complete your purchase here:\n{{checkout_url}}',
  popular_searches: row.popular_searches ?? 'Co-ord Sets, Sonic, Graphic Tee, T-shirt, Kids',

  postex_enabled: row.postex_enabled ?? false,
  postex_mode: row.postex_mode ?? 'sandbox',
  postex_pickup_address: row.postex_pickup_address ?? '',
  postex_return_address: row.postex_return_address ?? '',
  postex_order_type: row.postex_order_type ?? '',
  postex_handling_type: row.postex_handling_type ?? '',
  postex_default_remarks: row.postex_default_remarks ?? '',
  postex_pickup_display: row.postex_pickup_display ?? '',
  postex_return_display: row.postex_return_display ?? '',
  postex_return_city: row.postex_return_city ?? '',
  postex_product_check: row.postex_product_check ?? '1',
  postex_sku_check: row.postex_sku_check ?? '0',
  postex_weight_check: row.postex_weight_check ?? '1',
  postex_pieces_check: row.postex_pieces_check ?? '1',
  postex_cod_check: row.postex_cod_check ?? '0',
  postex_notes_check: row.postex_notes_check ?? '1',
  postex_default_weight: row.postex_default_weight ?? '0.5',
  postex_default_items: row.postex_default_items ?? '3',
  postex_default_product: row.postex_default_product ?? 'General Items',
  postex_whatsapp_template: row.postex_whatsapp_template ?? 'Dear {name}, your order has been booked. You can track it here: {url}\n{note}',
  postex_whatsapp_note: row.postex_whatsapp_note ?? 'Thank you for shopping with us!',
  postex_auto_download_label: row.postex_auto_download_label ?? false,

  updated_at: row.updated_at
});

export const mapAdminSettings = (row: any): StoreSettings => {
  const settings = mapSettings(row);
  // Pass secret fields through as-stored (may be encrypted `enc:v1:` envelopes).
  // getAdminSettings() decrypts them server-side before returning to the admin
  // form. We only pre-parse ai_model_credentials when it is plain JSON so legacy
  // plaintext rows keep working; encrypted strings are passed through untouched.
  let creds: any = {};
  const rawCreds = row.ai_model_credentials;
  if (typeof rawCreds === 'string' && rawCreds.startsWith('enc:v1:')) {
    creds = rawCreds; // encrypted; decrypted downstream
  } else {
    try {
      creds = typeof rawCreds === 'string' ? JSON.parse(rawCreds) : (rawCreds || {});
    } catch {
      creds = {};
    }
  }
  return {
    ...settings,
    ai_model_credentials: creds,
    content_keys: row.content_keys ?? '',
    vision_keys: row.vision_keys ?? '',
    smtp_app_password: row.smtp_app_password ?? '',
    postex_api_token: row.postex_api_token ?? '',
  };
};
