'use client';

import { StoreSettings } from '@/lib/types';
import { cleanWhatsAppPhone } from '@/lib/utils/whatsapp';

export function buildSettingsPayload(data: {
  storeName: string;
  storeUrl: string;
  orderPrefix: string;
  nextOrderSequenceDirty: boolean;
  nextOrderSequence: number;
  cleanPhone: string;
  currency: string;
  currencySymbol: string;
  logoUrl: string;
  logoWidth: number;
  bannerUrl: string;
  faviconUrl: string;
  tagline: string;
  address: string;
  showStock: boolean;
  showComparePrice: boolean;
  enableSearch: boolean;
  enableCategoryFilter: boolean;
  whatsappGreeting: string;
  whatsappFooter: string;
  popularSearches: string;
  footerText: string;
  socialFacebook: string;
  socialInstagram: string;
  socialWhatsapp: string;
  socialYoutube: string;
  trustProducts: any;
  headerFooter: any;
  navigation: any;
  popupsPixels: any;
  mediaUploads: any;
  socialFeed: any;
  aiEmails: any;
}): Partial<StoreSettings> {
  const {
    storeName,
    storeUrl,
    orderPrefix,
    nextOrderSequenceDirty,
    nextOrderSequence,
    cleanPhone,
    currency,
    currencySymbol,
    logoWidth,
    tagline,
    address,
    showStock,
    showComparePrice,
    enableSearch,
    enableCategoryFilter,
    whatsappGreeting,
    whatsappFooter,
    popularSearches,
    footerText,
    socialFacebook,
    socialInstagram,
    socialWhatsapp,
    socialYoutube,
    trustProducts,
    headerFooter,
    navigation,
    popupsPixels,
    mediaUploads,
    socialFeed,
    aiEmails,
  } = data;

  return {
    store_name: storeName.trim(),
    store_url: storeUrl.trim(),
    order_prefix: orderPrefix.trim(),
    ...(nextOrderSequenceDirty ? { next_order_sequence: nextOrderSequence } : {}),
    whatsapp_number: cleanPhone,
    currency: currency.trim(),
    currency_symbol: currencySymbol.trim(),
    logo_url: mediaUploads.logoUrl.trim() || undefined,
    logo_width: Number(logoWidth),
    banner_url: mediaUploads.bannerUrl.trim() || undefined,
    favicon_url: mediaUploads.faviconUrl.trim() || undefined,
    tagline: tagline.trim() || undefined,
    address: address.trim() || undefined,
    show_stock: showStock,
    show_compare_price: showComparePrice,
    enable_search: enableSearch,
    enable_category_filter: enableCategoryFilter,
    whatsapp_greeting: whatsappGreeting.trim(),
    whatsapp_footer: whatsappFooter.trim(),
    popular_searches: popularSearches.trim(),
    footer_text: footerText.trim() || undefined,
    social_facebook: socialFacebook.trim() || undefined,
    social_instagram: socialInstagram.trim() || undefined,
    social_whatsapp: cleanWhatsAppPhone(socialWhatsapp) || undefined,
    social_youtube: socialYoutube.trim() || undefined,
    enable_fake_views: trustProducts.enableFakeViews,
    min_views: Number(trustProducts.minViews),
    max_views: Number(trustProducts.maxViews),
    enable_trust_badges: trustProducts.enableTrustBadges,
    delivery_estimate_text: trustProducts.deliveryEstimateText.trim(),
    free_shipping_text: trustProducts.freeShippingText.trim(),
    promo_code_text: trustProducts.promoCodeText.trim(),
    enable_safe_checkout: trustProducts.enableSafeCheckout,
    safe_checkout_text: trustProducts.safeCheckoutText.trim(),
    safe_checkout_methods: trustProducts.safeCheckoutMethods,
    enable_ticker: trustProducts.enableTicker,
    ticker_text: trustProducts.tickerText.trim(),
    enable_variant_swatches: trustProducts.enableVariantSwatches,
    swatch_shape: trustProducts.swatchShape,
    swatch_size: trustProducts.swatchSize,
    swatch_limit: Number(trustProducts.swatchLimit) || 8,
    default_variant_index: Number(trustProducts.defaultVariantIndex) || 1,
    image_hover_style: trustProducts.imageHoverStyle,
    image_aspect_ratio: trustProducts.imageAspectRatio,
    title_line_limit: trustProducts.titleLineLimit,
    archive_swatch_size: trustProducts.archiveSwatchSize,
    product_swatch_size: trustProducts.productSwatchSize,
    archive_swatch_align: trustProducts.archiveSwatchAlign,
    card_show_description: trustProducts.cardShowDescription,
    card_show_swatches: trustProducts.cardShowSwatches,
    card_show_sizes: trustProducts.cardShowSizes,
    card_show_materials: trustProducts.cardShowMaterials,
    card_show_custom: trustProducts.cardShowCustom,
    card_show_custom_2: trustProducts.cardShowCustom2,
    card_show_type_color: trustProducts.cardShowTypeColor,
    card_show_type_size: trustProducts.cardShowTypeSize,
    card_show_type_material: trustProducts.cardShowTypeMaterial,
    card_show_type_custom: trustProducts.cardShowTypeCustom,
    card_mobile_columns: trustProducts.cardMobileColumns,
    header_sticky: headerFooter.headerSticky,
    header_sticky_desktop: headerFooter.headerStickyDesktop,
    header_sticky_mobile: headerFooter.headerStickyMobile,
    header_show_top_bar: headerFooter.headerShowTopBar,
    header_top_bar_phone: headerFooter.headerTopBarPhone,
    header_top_bar_email: headerFooter.headerTopBarEmail,
    header_show_newsletter: headerFooter.headerShowNewsletter,
    header_newsletter_text: headerFooter.headerNewsletterText,
    header_top_bar_bg: headerFooter.headerTopBarBg,
    header_top_bar_text_color: headerFooter.headerTopBarTextColor,
    header_bg: headerFooter.headerBg,
    header_text_color: headerFooter.headerTextColor,
    header_border_color: headerFooter.headerBorderColor,
    header_desktop_logo_align: headerFooter.headerDesktopLogoAlign,
    header_desktop_search_align: headerFooter.headerDesktopSearchAlign,
    header_desktop_wishlist_align: headerFooter.headerDesktopWishlistAlign,
    header_desktop_cart_align: headerFooter.headerDesktopCartAlign,
    header_desktop_theme_align: headerFooter.headerDesktopThemeAlign,
    header_mobile_logo_align: headerFooter.headerMobileLogoAlign,
    header_mobile_menu_align: headerFooter.headerMobileMenuAlign,
    header_mobile_search_align: headerFooter.headerMobileSearchAlign,
    header_mobile_cart_align: headerFooter.headerMobileCartAlign,
    header_mobile_wishlist_align: headerFooter.headerMobileWishlistAlign,
    navigation_menu: navigation.navigationMenu,
    header_desktop_menu_align: headerFooter.headerDesktopMenuAlign,
    faq_content: trustProducts.faqContent.trim(),
    return_policy_content: trustProducts.returnPolicyContent.trim(),
    privacy_policy_content: trustProducts.privacyPolicyContent.trim(),
    show_faq_in_nav: trustProducts.showFaqInNav,
    show_returns_in_nav: trustProducts.showReturnsInNav,
    show_privacy_in_nav: trustProducts.showPrivacyInNav,
    show_faq_in_footer: trustProducts.showFaqInFooter,
    show_returns_in_footer: trustProducts.showReturnsInFooter,
    show_privacy_in_footer: trustProducts.showPrivacyInFooter,
    trust_badge1_title: trustProducts.trustBadge1Title.trim(),
    trust_badge1_desc: trustProducts.trustBadge1Desc.trim(),
    trust_badge1_icon: trustProducts.trustBadge1Icon.trim(),
    trust_badge2_title: trustProducts.trustBadge2Title.trim(),
    trust_badge2_desc: trustProducts.trustBadge2Desc.trim(),
    trust_badge2_icon: trustProducts.trustBadge2Icon.trim(),
    trust_badge3_title: trustProducts.trustBadge3Title.trim(),
    trust_badge3_desc: trustProducts.trustBadge3Desc.trim(),
    trust_badge3_icon: trustProducts.trustBadge3Icon.trim(),
    trust_badge4_title: trustProducts.trustBadge4Title.trim(),
    trust_badge4_desc: trustProducts.trustBadge4Desc.trim(),
    trust_badge4_icon: trustProducts.trustBadge4Icon.trim(),
    trust_badge1_enabled: trustProducts.trustBadge1Enabled,
    trust_badge2_enabled: trustProducts.trustBadge2Enabled,
    trust_badge3_enabled: trustProducts.trustBadge3Enabled,
    trust_badge4_enabled: trustProducts.trustBadge4Enabled,
    social_tiktok: headerFooter.socialTiktok.trim(),
    social_snapchat: headerFooter.socialSnapchat.trim(),
    social_twitter: headerFooter.socialTwitter.trim(),
    footer_col1_title: headerFooter.footerCol1Title.trim(),
    footer_col2_title: headerFooter.footerCol2Title.trim(),
    footer_col2_text: headerFooter.footerCol2Text.trim(),
    footer_col3_title: headerFooter.footerCol3Title.trim(),
    footer_col4_title: headerFooter.footerCol4Title.trim(),
    footer_col4_text: headerFooter.footerCol4Text.trim(),
    footer_bottom_text: headerFooter.footerBottomText.trim(),
    footer_show_payments: headerFooter.footerShowPayments,
    footer_show_menu: headerFooter.footerShowMenu,
    footer_show_newsletter: headerFooter.footerShowNewsletter,
    footer_show_social: headerFooter.footerShowSocial,
    floating_contacts_enabled: headerFooter.floatingContactsEnabled,
    floating_contacts_position: headerFooter.floatingContactsPosition,
    floating_contacts_bottom_mobile: Number(headerFooter.floatingContactsBottomMobile),
    floating_contacts_bottom_desktop: Number(headerFooter.floatingContactsBottomDesktop),
    floating_contacts_side_mobile: Number(headerFooter.floatingContactsSideMobile),
    floating_contacts_side_desktop: Number(headerFooter.floatingContactsSideDesktop),
    floating_contacts_scale: Number(headerFooter.floatingContactsScale),
    floating_whatsapp_preset: headerFooter.floatingWhatsappPreset.trim(),
    floating_whatsapp_number: headerFooter.floatingWhatsappNumber.trim()
      ? cleanWhatsAppPhone(headerFooter.floatingWhatsappNumber.trim())
      : '',
    floating_whatsapp_enabled: headerFooter.floatingWhatsappEnabled,
    floating_instagram_enabled: headerFooter.floatingInstagramEnabled,
    floating_tiktok_enabled: headerFooter.floatingTiktokEnabled,
    floating_snapchat_enabled: headerFooter.floatingSnapchatEnabled,
    floating_twitter_enabled: headerFooter.floatingTwitterEnabled,
    exit_intent_enabled: popupsPixels.exitIntentEnabled,
    exit_intent_title: popupsPixels.exitIntentTitle.trim(),
    exit_intent_text: popupsPixels.exitIntentText.trim(),
    exit_intent_coupon: popupsPixels.exitIntentCoupon.trim().toUpperCase(),
    spin_wheel_enabled: popupsPixels.spinWheelEnabled,
    spin_wheel_segments: popupsPixels.spinWheelSegments,
    cart_timer_minutes: Number(popupsPixels.cartTimerMinutes),
    free_shipping_threshold: Number(popupsPixels.freeShippingThreshold),
    volume_discount_threshold: Number(popupsPixels.volumeDiscountThreshold),
    volume_discount_percentage: Number(popupsPixels.volumeDiscountPercentage),
    recent_buyers: popupsPixels.recentBuyersPairs,
    recently_viewed_limit: Number(popupsPixels.recentlyViewedLimit),
    recent_buyers_enabled: popupsPixels.recentBuyersEnabled,
    cookie_consent_enabled: popupsPixels.cookieConsentEnabled,
    free_shipping_bar_enabled: popupsPixels.freeShippingBarEnabled,
    volume_discounts_enabled: popupsPixels.volumeDiscountsEnabled,
    frequently_bought_together_enabled: popupsPixels.frequentlyBoughtTogetherEnabled,
    stock_urgency_enabled: popupsPixels.stockUrgencyEnabled,
    flash_sale_enabled: popupsPixels.flashSaleEnabled,
    flash_sale_start_date: popupsPixels.flashSaleStartDate || null,
    flash_sale_end_date: popupsPixels.flashSaleEndDate || null,
    global_flash_sale_discount_type: popupsPixels.globalFlashSaleDiscountType,
    global_flash_sale_discount_value: popupsPixels.globalFlashSaleDiscountValue,
    social_feeds_enabled: popupsPixels.socialFeedsEnabled,
    cart_timer_enabled: popupsPixels.cartTimerEnabled,
    size_guide_enabled: popupsPixels.sizeGuideEnabled,
    recent_buyers_names: popupsPixels.recentBuyersNames.trim(),
    recent_buyers_cities: popupsPixels.recentBuyersCities.trim(),
    recent_buyers_source: popupsPixels.recentBuyersSource,
    recent_buyers_product_pool: popupsPixels.recentBuyersProductPool,
    recent_buyers_custom_products: popupsPixels.recentBuyersCustomProducts,
    recent_buyers_initial_delay: Number(popupsPixels.recentBuyersInitialDelay),
    recent_buyers_interval: Number(popupsPixels.recentBuyersInterval),
    recent_buyers_display_duration: Number(popupsPixels.recentBuyersDisplayDuration),
    recent_buyers_show_on_checkout: popupsPixels.recentBuyersShowOnCheckout,
    exit_intent_image_url: mediaUploads.exitIntentImageUrl.trim(),
    exit_intent_delay_mobile: Number(popupsPixels.exitIntentDelayMobile),
    cookie_consent_text: popupsPixels.cookieConsentText.trim(),
    cookie_consent_button_text: popupsPixels.cookieConsentButtonText.trim(),
    social_feeds_homepage_enabled: popupsPixels.socialFeedsHomepageEnabled,
    social_feeds_product_enabled: popupsPixels.socialFeedsProductEnabled,
    social_feeds_title: popupsPixels.socialFeedsTitle.trim(),
    social_feeds_subtitle: popupsPixels.socialFeedsSubtitle.trim(),
    social_feeds_desc: popupsPixels.socialFeedsDesc.trim(),
    social_feeds_items: socialFeed.socialFeedsItems,
    cart_timer_message: popupsPixels.cartTimerMessage.trim(),
    coupon_codes_enabled: popupsPixels.couponCodesEnabled,
    meta_pixel_id: popupsPixels.metaPixelId.trim(),
    meta_sync_enabled: popupsPixels.metaSyncEnabled,
    ga4_measurement_id: popupsPixels.ga4MeasurementId.trim(),
    gtm_container_id: popupsPixels.gtmContainerId.trim(),
    tiktok_pixel_id: popupsPixels.tiktokPixelId.trim(),
    twitter_pixel_id: popupsPixels.twitterPixelId.trim(),
    snapchat_pixel_id: popupsPixels.snapchatPixelId.trim(),
    pinterest_tag_id: popupsPixels.pinterestTagId.trim(),
    twitter_handle: popupsPixels.twitterHandle.trim(),
    meta_title_suffix: popupsPixels.metaTitleSuffix.trim(),
    meta_title: popupsPixels.metaTitle.trim(),
    meta_description: popupsPixels.metaDescription.trim(),
    ai_enabled: aiEmails.aiEnabled,
    ai_model_credentials: aiEmails.aiModelCredentials,
    content_keys: (aiEmails.aiModelCredentials?.content?.[aiEmails.contentProvider.trim()] || '').trim(),
    vision_keys: (aiEmails.aiModelCredentials?.vision?.[aiEmails.visionProvider.trim()] || '').trim(),
    ai_persona_config: aiEmails.aiPersonaConfig,
    content_provider: aiEmails.contentProvider.trim(),
    content_model: aiEmails.contentModel.trim(),
    vision_provider: aiEmails.visionProvider.trim(),
    vision_model: aiEmails.visionModel.trim(),
    ai_tone: aiEmails.aiPersonaConfig.tone,
    ai_language: aiEmails.aiPersonaConfig.language,
    ai_custom_instructions: aiEmails.aiPersonaConfig.customInstructions,
    target_audiences: (aiEmails.aiPersonaConfig.targetAudiences || []).join(', '),
    product_types: (aiEmails.aiPersonaConfig.productTypes || []).join(', '),
    auto_content_seo: aiEmails.autoContentSeo,
    auto_media_ai: aiEmails.autoMediaAi,
    category_default_template: aiEmails.categoryDefaultTemplate.trim(),
    product_default_template: aiEmails.productDefaultTemplate.trim(),
    category_description_prompt: aiEmails.categoryDescriptionPrompt.trim(),
    category_description_limit: Number(aiEmails.categoryDescriptionLimit) || 150,
    product_description_prompt: aiEmails.productDescriptionPrompt.trim(),
    product_description_limit: Number(aiEmails.productDescriptionLimit) || 250,
    product_short_prompt: aiEmails.productShortPrompt.trim(),
    product_short_limit: Number(aiEmails.productShortLimit) || 100,
    collection_default_template: aiEmails.collectionDefaultTemplate.trim(),
    collection_description_prompt: aiEmails.collectionDescriptionPrompt.trim(),
    collection_description_limit: Number(aiEmails.collectionDescriptionLimit) || 150,
    smtp_email: aiEmails.smtpEmail.trim(),
    smtp_app_password: aiEmails.smtpAppPassword.trim(),
    smtp_from_name: aiEmails.smtpFromName.trim(),
    admin_notification_email: aiEmails.adminNotificationEmail.trim(),
    email_notifications: aiEmails.emailNotifications,
    low_stock_threshold: Number(aiEmails.lowStockThreshold) || 5,
    abandoned_cart_email_enabled: aiEmails.abandonedCartEmailEnabled,
    abandoned_cart_admin_notify: aiEmails.abandonedCartAdminNotify,
    abandoned_cart_email_subject: aiEmails.abandonedCartEmailSubject.trim(),
    abandoned_cart_email_template: aiEmails.abandonedCartEmailTemplate.trim(),
  };
}
