'use client';

import { StoreSettings } from '@/lib/types';
import { cleanWhatsAppPhone } from '@/lib/utils/whatsapp';

export function buildSettingsPayload(data: {
  storeName: string;
  storeUrl: string;
  orderPrefix: string;
  nextOrderSequenceDirty: boolean;
  nextOrderSequence: number;
  cleanPhone: string;
  currency: string;
  currencySymbol: string;
  logoUrl: string;
  logoWidth: number;
  bannerUrl: string;
  faviconUrl: string;
  tagline: string;
  address: string;
  showStock: boolean;
  showComparePrice: boolean;
  enableSearch: boolean;
  enableCategoryFilter: boolean;
  whatsappGreeting: string;
  whatsappFooter: string;
  popularSearches: string;
  footerText: string;
  socialFacebook: string;
  socialInstagram: string;
  socialWhatsapp: string;
  socialYoutube: string;
  trustProducts: any;
  headerFooter: any;
  navigation: any;
  popupsPixels: any;
  mediaUploads: any;
  socialFeed: any;
  aiEmails: any;
}): Partial<StoreSettings> {
  const {
    storeName,
    storeUrl,
    orderPrefix,
    nextOrderSequenceDirty,
    nextOrderSequence,
    cleanPhone,
    currency,
    currencySymbol,
    logoWidth,
    tagline,
    address,
    showStock,
    showComparePrice,
    enableSearch,
    enableCategoryFilter,
    whatsappGreeting,
    whatsappFooter,
    popularSearches,
    footerText,
    socialFacebook,
    socialInstagram,
    socialWhatsapp,
    socialYoutube,
    trustProducts,
    headerFooter,
    navigation,
    popupsPixels,
    mediaUploads,
    socialFeed,
    aiEmails,
  } = data;

  return {
    storeName: storeName.trim(),
    storeUrl: storeUrl.trim(),
    orderPrefix: orderPrefix.trim(),
    ...(nextOrderSequenceDirty ? { nextOrderSequence } : {}),
    whatsappNumber: cleanPhone,
    currency: currency.trim(),
    currencySymbol: currencySymbol.trim(),
    logoUrl: mediaUploads.logoUrl.trim() || undefined,
    logoWidth: Number(logoWidth),
    bannerUrl: mediaUploads.bannerUrl.trim() || undefined,
    faviconUrl: mediaUploads.faviconUrl.trim() || undefined,
    tagline: tagline.trim() || undefined,
    address: address.trim() || undefined,
    showStock,
    showComparePrice,
    enableSearch,
    enableCategoryFilter,
    whatsappGreeting: whatsappGreeting.trim(),
    whatsappFooter: whatsappFooter.trim(),
    popularSearches: popularSearches.trim(),
    footerText: footerText.trim() || undefined,
    socialFacebook: socialFacebook.trim() || undefined,
    socialInstagram: socialInstagram.trim() || undefined,
    socialWhatsapp: cleanWhatsAppPhone(socialWhatsapp) || undefined,
    socialYoutube: socialYoutube.trim() || undefined,
    enableFakeViews: trustProducts.enableFakeViews,
    minViews: Number(trustProducts.minViews),
    maxViews: Number(trustProducts.maxViews),
    enableTrustBadges: trustProducts.enableTrustBadges,
    deliveryEstimateText: trustProducts.deliveryEstimateText.trim(),
    freeShippingText: trustProducts.freeShippingText.trim(),
    promoCodeText: trustProducts.promoCodeText.trim(),
    enableSafeCheckout: trustProducts.enableTrustBadges,
    safeCheckoutText: trustProducts.safeCheckoutText.trim(),
    safeCheckoutMethods: trustProducts.safeCheckoutMethods,
    enableTicker: trustProducts.enableTicker,
    tickerText: trustProducts.tickerText.trim(),
    enableVariantSwatches: trustProducts.enableVariantSwatches,
    swatchShape: trustProducts.swatchShape,
    swatchSize: trustProducts.swatchSize,
    swatchLimit: Number(trustProducts.swatchLimit) || 8,
    defaultVariantIndex: Number(trustProducts.defaultVariantIndex) || 1,
    imageHoverStyle: trustProducts.imageHoverStyle,
    imageAspectRatio: trustProducts.imageAspectRatio,
    titleLineLimit: trustProducts.titleLineLimit,
    archiveSwatchSize: trustProducts.archiveSwatchSize,
    productSwatchSize: trustProducts.productSwatchSize,
    archiveSwatchAlign: trustProducts.archiveSwatchAlign,
    card_show_description: trustProducts.cardShowDescription,
    card_show_swatches: trustProducts.cardShowSwatches,
    card_show_sizes: trustProducts.cardShowSizes,
    card_show_materials: trustProducts.cardShowMaterials,
    card_show_custom: trustProducts.cardShowCustom,
    card_show_custom_2: trustProducts.cardShowCustom2,
    card_show_type_color: trustProducts.cardShowTypeColor,
    card_show_type_size: trustProducts.cardShowTypeSize,
    card_show_type_material: trustProducts.cardShowTypeMaterial,
    card_show_type_custom: trustProducts.cardShowTypeCustom,
    card_mobile_columns: trustProducts.cardMobileColumns,
    headerSticky: headerFooter.headerSticky,
    headerStickyDesktop: headerFooter.headerStickyDesktop,
    headerStickyMobile: headerFooter.headerStickyMobile,
    headerShowTopBar: headerFooter.headerShowTopBar,
    headerTopBarPhone: headerFooter.headerTopBarPhone,
    headerTopBarEmail: headerFooter.headerTopBarEmail,
    headerShowNewsletter: headerFooter.headerShowNewsletter,
    headerNewsletterText: headerFooter.headerNewsletterText,
    headerTopBarBg: headerFooter.headerTopBarBg,
    headerTopBarTextColor: headerFooter.headerTopBarTextColor,
    headerBg: headerFooter.headerBg,
    headerTextColor: headerFooter.headerTextColor,
    headerBorderColor: headerFooter.headerBorderColor,
    headerDesktopLogoAlign: headerFooter.headerDesktopLogoAlign,
    headerDesktopSearchAlign: headerFooter.headerDesktopSearchAlign,
    headerDesktopWishlistAlign: headerFooter.headerDesktopWishlistAlign,
    headerDesktopCartAlign: headerFooter.headerDesktopCartAlign,
    headerDesktopThemeAlign: headerFooter.headerDesktopThemeAlign,
    headerMobileLogoAlign: headerFooter.headerMobileLogoAlign,
    headerMobileMenuAlign: headerFooter.headerMobileMenuAlign,
    headerMobileSearchAlign: headerFooter.headerMobileSearchAlign,
    headerMobileCartAlign: headerFooter.headerMobileCartAlign,
    headerMobileWishlistAlign: headerFooter.headerMobileWishlistAlign,
    navigationMenu: navigation.navigationMenu,
    headerDesktopMenuAlign: headerFooter.headerDesktopMenuAlign,
    faqContent: trustProducts.faqContent.trim(),
    returnPolicyContent: trustProducts.returnPolicyContent.trim(),
    privacyPolicyContent: trustProducts.privacyPolicyContent.trim(),
    showFaqInNav: trustProducts.showFaqInNav,
    showReturnsInNav: trustProducts.showReturnsInNav,
    showPrivacyInNav: trustProducts.showPrivacyInNav,
    showFaqInFooter: trustProducts.showFaqInFooter,
    showReturnsInFooter: trustProducts.showReturnsInFooter,
    showPrivacyInFooter: trustProducts.showPrivacyInFooter,
    trustBadge1Title: trustProducts.trustBadge1Title.trim(),
    trustBadge1Desc: trustProducts.trustBadge1Desc.trim(),
    trustBadge1Icon: trustProducts.trustBadge1Icon.trim(),
    trustBadge2Title: trustProducts.trustBadge2Title.trim(),
    trustBadge2Desc: trustProducts.trustBadge2Desc.trim(),
    trustBadge2Icon: trustProducts.trustBadge2Icon.trim(),
    trustBadge3Title: trustProducts.trustBadge3Title.trim(),
    trustBadge3Desc: trustProducts.trustBadge3Desc.trim(),
    trustBadge3Icon: trustProducts.trustBadge3Icon.trim(),
    trustBadge4Title: trustProducts.trustBadge4Title.trim(),
    trustBadge4Desc: trustProducts.trustBadge4Desc.trim(),
    trustBadge4Icon: trustProducts.trustBadge4Icon.trim(),
    trustBadge1Enabled: trustProducts.trustBadge1Enabled,
    trustBadge2Enabled: trustProducts.trustBadge2Enabled,
    trustBadge3Enabled: trustProducts.trustBadge3Enabled,
    trustBadge4Enabled: trustProducts.trustBadge4Enabled,
    socialTiktok: headerFooter.socialTiktok.trim(),
    socialSnapchat: headerFooter.socialSnapchat.trim(),
    socialTwitter: headerFooter.socialTwitter.trim(),
    footerCol1Title: headerFooter.footerCol1Title.trim(),
    footerCol2Title: headerFooter.footerCol2Title.trim(),
    footerCol2Text: headerFooter.footerCol2Text.trim(),
    footerCol3Title: headerFooter.footerCol3Title.trim(),
    footerCol4Title: headerFooter.footerCol4Title.trim(),
    footerCol4Text: headerFooter.footerCol4Text.trim(),
    footerBottomText: headerFooter.footerBottomText.trim(),
    footerShowPayments: headerFooter.footerShowPayments,
    footerShowMenu: headerFooter.footerShowMenu,
    footerShowNewsletter: headerFooter.footerShowNewsletter,
    footerShowSocial: headerFooter.footerShowSocial,
    floatingContactsEnabled: headerFooter.floatingContactsEnabled,
    floatingContactsPosition: headerFooter.floatingContactsPosition,
    floatingContactsBottomMobile: Number(headerFooter.floatingContactsBottomMobile),
    floatingContactsBottomDesktop: Number(headerFooter.floatingContactsBottomDesktop),
    floatingContactsSideMobile: Number(headerFooter.floatingContactsSideMobile),
    floatingContactsSideDesktop: Number(headerFooter.floatingContactsSideDesktop),
    floatingContactsScale: Number(headerFooter.floatingContactsScale),
    floatingWhatsappPreset: headerFooter.floatingWhatsappPreset.trim(),
    floatingWhatsappNumber: headerFooter.floatingWhatsappNumber.trim()
      ? cleanWhatsAppPhone(headerFooter.floatingWhatsappNumber.trim())
      : '',
    floatingWhatsappEnabled: headerFooter.floatingWhatsappEnabled,
    floatingInstagramEnabled: headerFooter.floatingInstagramEnabled,
    floatingTiktokEnabled: headerFooter.floatingTiktokEnabled,
    floatingSnapchatEnabled: headerFooter.floatingSnapchatEnabled,
    floatingTwitterEnabled: headerFooter.floatingTwitterEnabled,
    exit_intent_enabled: popupsPixels.exitIntentEnabled,
    exit_intent_title: popupsPixels.exitIntentTitle.trim(),
    exit_intent_text: popupsPixels.exitIntentText.trim(),
    exit_intent_coupon: popupsPixels.exitIntentCoupon.trim().toUpperCase(),
    spin_wheel_enabled: popupsPixels.spinWheelEnabled,
    spin_wheel_segments: popupsPixels.spinWheelSegments,
    cart_timer_minutes: Number(popupsPixels.cartTimerMinutes),
    free_shipping_threshold: Number(popupsPixels.freeShippingThreshold),
    volume_discount_threshold: Number(popupsPixels.volumeDiscountThreshold),
    volume_discount_percentage: Number(popupsPixels.volumeDiscountPercentage),
    recent_buyers: popupsPixels.recentBuyersStr.trim(),
    recently_viewed_limit: Number(popupsPixels.recentlyViewedLimit),
    recent_buyers_enabled: popupsPixels.recentBuyersEnabled,
    cookie_consent_enabled: popupsPixels.cookieConsentEnabled,
    free_shipping_bar_enabled: popupsPixels.freeShippingBarEnabled,
    volume_discounts_enabled: popupsPixels.volumeDiscountsEnabled,
    frequently_bought_together_enabled: popupsPixels.frequentlyBoughtTogetherEnabled,
    stock_urgency_enabled: popupsPixels.stockUrgencyEnabled,
    flash_sale_enabled: popupsPixels.flashSaleEnabled,
    flash_sale_start_date: popupsPixels.flashSaleStartDate || null,
    flash_sale_end_date: popupsPixels.flashSaleEndDate || null,
    globalFlashSaleDiscountType: popupsPixels.globalFlashSaleDiscountType,
    globalFlashSaleDiscountValue: popupsPixels.globalFlashSaleDiscountValue,
    social_feeds_enabled: popupsPixels.socialFeedsEnabled,
    cart_timer_enabled: popupsPixels.cartTimerEnabled,
    size_guide_enabled: popupsPixels.sizeGuideEnabled,
    recent_buyers_names: popupsPixels.recentBuyersNames.trim(),
    recent_buyers_cities: popupsPixels.recentBuyersCities.trim(),
    recent_buyers_source: popupsPixels.recentBuyersSource,
    recent_buyers_product_pool: popupsPixels.recentBuyersProductPool,
    recent_buyers_custom_products: popupsPixels.recentBuyersCustomProducts,
    recent_buyers_initial_delay: Number(popupsPixels.recentBuyersInitialDelay),
    recent_buyers_interval: Number(popupsPixels.recentBuyersInterval),
    recent_buyers_display_duration: Number(popupsPixels.recentBuyersDisplayDuration),
    recent_buyers_show_on_checkout: popupsPixels.recentBuyersShowOnCheckout,
    exit_intent_image_url: mediaUploads.exitIntentImageUrl.trim(),
    exit_intent_delay_mobile: Number(popupsPixels.exitIntentDelayMobile),
    cookie_consent_text: popupsPixels.cookieConsentText.trim(),
    cookie_consent_button_text: popupsPixels.cookieConsentButtonText.trim(),
    social_feeds_homepage_enabled: popupsPixels.socialFeedsHomepageEnabled,
    social_feeds_product_enabled: popupsPixels.socialFeedsProductEnabled,
    social_feeds_title: popupsPixels.socialFeedsTitle.trim(),
    social_feeds_subtitle: popupsPixels.socialFeedsSubtitle.trim(),
    social_feeds_desc: popupsPixels.socialFeedsDesc.trim(),
    social_feeds_items: socialFeed.socialFeedsItems,
    cart_timer_message: popupsPixels.cartTimerMessage.trim(),
    coupon_codes_enabled: popupsPixels.couponCodesEnabled,
    meta_pixel_id: popupsPixels.metaPixelId.trim(),
    meta_sync_enabled: popupsPixels.metaSyncEnabled,
    ga4_measurement_id: popupsPixels.ga4MeasurementId.trim(),
    gtm_container_id: popupsPixels.gtmContainerId.trim(),
    tiktok_pixel_id: popupsPixels.tiktokPixelId.trim(),
    twitter_pixel_id: popupsPixels.twitterPixelId.trim(),
    snapchat_pixel_id: popupsPixels.snapchatPixelId.trim(),
    pinterest_tag_id: popupsPixels.pinterestTagId.trim(),
    twitter_handle: popupsPixels.twitterHandle.trim(),
    meta_title_suffix: popupsPixels.metaTitleSuffix.trim(),
    metaTitle: popupsPixels.metaTitle.trim(),
    metaDescription: popupsPixels.metaDescription.trim(),
    ai_enabled: aiEmails.aiEnabled,
    ai_model_credentials: aiEmails.aiModelCredentials,
    ai_persona_config: aiEmails.aiPersonaConfig,
    content_provider: aiEmails.contentProvider.trim(),
    content_model: aiEmails.contentModel.trim(),
    vision_provider: aiEmails.visionProvider.trim(),
    vision_model: aiEmails.visionModel.trim(),
    ai_tone: aiEmails.aiPersonaConfig.tone,
    ai_language: aiEmails.aiPersonaConfig.language,
    ai_custom_instructions: aiEmails.aiPersonaConfig.customInstructions,
    target_audiences: (aiEmails.aiPersonaConfig.targetAudiences || []).join(', '),
    product_types: (aiEmails.aiPersonaConfig.productTypes || []).join(', '),
    auto_content_seo: aiEmails.autoContentSeo,
    auto_media_ai: aiEmails.autoMediaAi,
    category_default_template: aiEmails.categoryDefaultTemplate.trim(),
    product_default_template: aiEmails.productDefaultTemplate.trim(),
    category_description_prompt: aiEmails.categoryDescriptionPrompt.trim(),
    category_description_limit: Number(aiEmails.categoryDescriptionLimit) || 150,
    product_description_prompt: aiEmails.productDescriptionPrompt.trim(),
    product_description_limit: Number(aiEmails.productDescriptionLimit) || 250,
    product_short_prompt: aiEmails.productShortPrompt.trim(),
    product_short_limit: Number(aiEmails.productShortLimit) || 100,
    collection_default_template: aiEmails.collectionDefaultTemplate.trim(),
    collection_description_prompt: aiEmails.collectionDescriptionPrompt.trim(),
    collection_description_limit: Number(aiEmails.collectionDescriptionLimit) || 150,
    smtp_email: aiEmails.smtpEmail.trim(),
    smtp_app_password: aiEmails.smtpAppPassword.trim(),
    smtp_from_name: aiEmails.smtpFromName.trim(),
    admin_notification_email: aiEmails.adminNotificationEmail.trim(),
    email_notifications: aiEmails.emailNotifications,
    low_stock_threshold: Number(aiEmails.lowStockThreshold) || 5,
    abandonedCartEmailEnabled: aiEmails.abandonedCartEmailEnabled,
    abandonedCartAdminNotify: aiEmails.abandonedCartAdminNotify,
    abandonedCartEmailSubject: aiEmails.abandonedCartEmailSubject.trim(),
    abandonedCartEmailTemplate: aiEmails.abandonedCartEmailTemplate.trim(),
  };
}
